### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by kildom** [kildom/filtry-ani#1]
* [] Zamknąć okna podglądy, wykresu itd. po wykonaniu operacji pluginu (Pojawia się co prawda tak jak należy okno output, ale nie są zamknięte te preview itd - pojawiają się jako możliwości wyboru w innych funkcjach image J)
* [] Zrobić, żeby ta proponowana krzywa jak się dopasowuje tylko pod punktami, albo nad szumem brała pod uwagę tylko te punkty albo tylko ten szum, bo chyba jakoś dziwnie działa)
* [x] Dodać podgląd wyniku również w przypadku trybu auto (może być tylko w wersji gdy jest jeden obrazek).
   * Checkbox, który włącza tą opcję,
   * Jeżeli zaznaczony, to w wynikowym obrazku będą na przemian oryginalny i wynikowy slice.
* [x] Ujednolicić w oknie parametrów czy używamy średnic czy promienia.
* [x] Zrobić opcję aby można było mieć wynik w postaci znalezionych punktów w ich oryginalnych odcieniach szarości.
* [x] TRUDNE - zrobić opcję obliczenia jasności punktów w odniesieniu do tła w ich otoczeniu.
* [x] Obliczać wszystko też przy granicy obrazka.
* [x] Bug: jeżeli zanaczenie wyjdzie poza wykres (np. przy przesuwaniu punktu) to jest exception
* [x] Bug: jeżeli się zamknie jakieś okno (inne niż dialogowe) w trybie manualnym, wyskakuje wyjątek
* [ ] Zaktualizować pomoc
* [x] Zmienić GUI
  * [x] Reset color balanse do części output parameters
  * [x] Przenieść opcje "Scaled" z listy do ticzka (domyślnie nie "scaled")
  * [x] Jeżeli scaled zaznaczone, wyświetl warning czy na pewno chcesz zrobić "scaled" (po wciśnięciu ok)
  * [x] Fixowanie parametru A  prostej podczas optymalizacji.
  * [x] Usunąć wiele przycisków help, powinien być jeden
  * [x] Przenieść "interactive mode" na górę okna.
  * [x] Uciąć paramtery prostej do kilku miejsc znaczących
  * [x] Wypisać inny komunikat, gdy jest odpowiednia liczba punktuów do "auto fitting", ale nie można wyliczyć.
* [x] Dokończyć reset display range

---------

* [x] Numeracja punktów na wykresie jak się da
* [x] Przyciski szum/punkt na obrazku podglądu jak się da
* [x] Przycisk wyznaczania prostej y=ax+b

---------

## Nie robić na razie

* [ ] *Dodać możliwość oddzielania punktów od tła za pomocą krzywej (nie tylko prostej)*
